# Build stage
FROM node:20 AS build-stage

# Pass the build argument to the environment
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN echo "VITE_API_URL is set to: $VITE_API_URL"
WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend ./
RUN npm run build

# Production stage
FROM nginx:stable-alpine AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./frontend/nginx /etc/nginx/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
