# Build stage
FROM node:20 AS build-stage

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend ./
RUN npm run build

# Production stage
FROM nginx:stable-alpine AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./frontend/nginx /etc/nginx/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
