{{- if .Values.pgbackup.enabled -}}
{{- $name := "db-backup" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "erebor.fullname" . }}-{{ $name }}
  namespace: {{ template "erebor.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- (include "erebor.commonLabels" .) | nindent 4 }}
  annotations:
    {{- (include "erebor.globalAnnotations" . ) | nindent 4 }}
spec:
  schedule: {{ default "0 2 * * *" .Values.pgbackup.schedule }} # This will run the job daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: {{ default "ghcr.io/Erebor-org/Erebor-toolbox:latest" .Values.pgbackup.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: {{ include "erebor.fullname" . }}-{{ $name }}-config
              command: ["sh", "/tmp/script.sh"]
              volumeMounts:
                - name: s3cfg
                  mountPath: /root/.s3cfg
                  subPath: s3cfg
                - name: script
                  mountPath: /tmp/script.sh
                  subPath: backup.sh
          restartPolicy: OnFailure
          {{- (include "erebor.imagePullSecrets" .) | nindent 10 }}
          volumes:
            - name: s3cfg
              configMap:
                name: {{ include "erebor.fullname" . }}-{{ $name }}-s3cfg-config
            - name: script
              configMap:
                name: {{ include "erebor.fullname" . }}-{{ $name }}-script
{{- end -}}