nelmio_cors:
  defaults:
    allow_credentials: true
    allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
    expose_headers: ["Link"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE", "PATCH"]
    max_age: 3600
    hosts: []
    origin_regex: true
