{{- $name := "pem-files" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "erebor.fullname" . }}-{{ $name }}
  namespace: {{ include "erebor.namespace" . }}
  labels:
    {{- (include "erebor.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
type: Opaque
data:
  JWT_PUBLIC_KEY_BASE64: {{ .Values.deployments.app.containers.symfony.jwt_keys.JWT_PUBLIC_KEY_BASE64 }}
  JWT_SECRET_KEY_BASE64: {{ .Values.deployments.app.containers.symfony.jwt_keys.JWT_SECRET_KEY_BASE64 }}
    
