{{- $name := "nginx" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "erebor.fullname" . }}-{{ $name }}-config
  namespace: {{ include "erebor.namespace" . }}
  labels:
    {{- (include "erebor.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
type: Opaque
data:
  {{- range $key, $value := .Values.deployments.app.containers.nginx.config }}
    {{ $key }}: {{ $value | toString| b64enc  }}
  {{- end }}