<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260819145317 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add ghost_round and ghost_vote tables for the Ghost Members admin voting feature, and seed the first open round.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE ghost_round (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              threshold INT NOT NULL,
              closed_by_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_976EFDE6E1FA7797 ON ghost_round (closed_by_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE ghost_vote (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              round_id INT NOT NULL,
              character_id INT NOT NULL,
              voter_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B2E561D7A6005CA0 ON ghost_vote (round_id)');
        $this->addSql('CREATE INDEX IDX_B2E561D71136BE75 ON ghost_vote (character_id)');
        $this->addSql('CREATE INDEX IDX_B2E561D7EBB4B8AD ON ghost_vote (voter_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_ghost_vote_round_character_voter ON ghost_vote (round_id, character_id, voter_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              ghost_round
            ADD
              CONSTRAINT FK_976EFDE6E1FA7797 FOREIGN KEY (closed_by_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              ghost_vote
            ADD
              CONSTRAINT FK_B2E561D7A6005CA0 FOREIGN KEY (round_id) REFERENCES ghost_round (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              ghost_vote
            ADD
              CONSTRAINT FK_B2E561D71136BE75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              ghost_vote
            ADD
              CONSTRAINT FK_B2E561D7EBB4B8AD FOREIGN KEY (voter_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO ghost_round (opened_at, closed_at, threshold)
            VALUES (NOW(), NULL, 4)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ghost_round DROP CONSTRAINT FK_976EFDE6E1FA7797');
        $this->addSql('ALTER TABLE ghost_vote DROP CONSTRAINT FK_B2E561D7A6005CA0');
        $this->addSql('ALTER TABLE ghost_vote DROP CONSTRAINT FK_B2E561D71136BE75');
        $this->addSql('ALTER TABLE ghost_vote DROP CONSTRAINT FK_B2E561D7EBB4B8AD');
        $this->addSql('DROP TABLE ghost_round');
        $this->addSql('DROP TABLE ghost_vote');
    }
}
