<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241202210123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(255) NOT NULL, ankama_pseudo VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, main_character_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4EA2EB0588E0BCC ON mule (main_character_id)');
        $this->addSql('ALTER TABLE mule ADD CONSTRAINT FK_4EA2EB0588E0BCC FOREIGN KEY (main_character_id) REFERENCES characters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mule DROP CONSTRAINT FK_4EA2EB0588E0BCC');
        $this->addSql('DROP TABLE mule');
    }
}
