<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260819115441 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop orphaned character-related tables that have no matching Doctrine entity anymore (character_availability, character_dungeon, character_profession, character_profile, character_quest, character_quest_combat, character_tags, dungeons_ref, professions_ref). All were empty at the time of this migration.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE character_availability DROP CONSTRAINT fk_e0d327d61136be75');
        $this->addSql('ALTER TABLE character_dungeon DROP CONSTRAINT fk_565f9fad1136be75');
        $this->addSql('ALTER TABLE character_profession DROP CONSTRAINT fk_b1fb4ef1136be75');
        $this->addSql('ALTER TABLE character_profile DROP CONSTRAINT fk_e8f22a321136be75');
        $this->addSql('ALTER TABLE character_quest DROP CONSTRAINT fk_bdd41f751136be75');
        $this->addSql('ALTER TABLE character_quest_combat DROP CONSTRAINT fk_abdf04071136be75');
        $this->addSql('ALTER TABLE character_tags DROP CONSTRAINT fk_784080be1136be75');
        $this->addSql('DROP TABLE character_availability');
        $this->addSql('DROP TABLE character_dungeon');
        $this->addSql('DROP TABLE character_profession');
        $this->addSql('DROP TABLE character_profile');
        $this->addSql('DROP TABLE character_quest');
        $this->addSql('DROP TABLE character_quest_combat');
        $this->addSql('DROP TABLE character_tags');
        $this->addSql('DROP TABLE dungeons_ref');
        $this->addSql('DROP TABLE professions_ref');
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE character_availability (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              timezone VARCHAR(100) DEFAULT NULL,
              slots_json JSON DEFAULT NULL,
              notes TEXT DEFAULT NULL,
              character_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_character_availability_character ON character_availability (character_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_e0d327d61136be75 ON character_availability (character_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE character_dungeon (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              dungeon_key VARCHAR(255) NOT NULL,
              can_help BOOLEAN NOT NULL,
              notes TEXT DEFAULT NULL,
              character_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_character_dungeon_can_help ON character_dungeon (can_help)');
        $this->addSql('CREATE INDEX idx_character_dungeon_character ON character_dungeon (character_id)');
        $this->addSql('CREATE INDEX idx_character_dungeon_key ON character_dungeon (dungeon_key)');
        $this->addSql(<<<'SQL'
            CREATE TABLE character_profession (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              profession_name VARCHAR(255) NOT NULL,
              level INT NOT NULL,
              character_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_character_profession_level ON character_profession (level)');
        $this->addSql('CREATE INDEX idx_character_profession_name ON character_profession (profession_name)');
        $this->addSql('CREATE INDEX idx_character_profession_character ON character_profession (character_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE character_profile (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              bio TEXT DEFAULT NULL,
              contact_preference VARCHAR(100) DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              character_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_e8f22a321136be75 ON character_profile (character_id)');
        $this->addSql('CREATE INDEX idx_character_profile_character ON character_profile (character_id)');
        $this->addSql('CREATE INDEX idx_character_profile_updated_at ON character_profile (updated_at)');
        $this->addSql(<<<'SQL'
            CREATE TABLE character_quest (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              quest_key VARCHAR(255) NOT NULL,
              step_or_stage VARCHAR(255) DEFAULT NULL,
              notes TEXT DEFAULT NULL,
              character_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_character_quest_character ON character_quest (character_id)');
        $this->addSql('CREATE INDEX idx_character_quest_key ON character_quest (quest_key)');
        $this->addSql(<<<'SQL'
            CREATE TABLE character_quest_combat (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              quest_combat_key VARCHAR(255) NOT NULL,
              notes TEXT DEFAULT NULL,
              character_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_character_quest_combat_key ON character_quest_combat (quest_combat_key)');
        $this->addSql('CREATE INDEX idx_character_quest_combat_character ON character_quest_combat (character_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE character_tags (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              tag VARCHAR(255) NOT NULL,
              character_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_character_tags_character ON character_tags (character_id)');
        $this->addSql('CREATE INDEX idx_character_tags_tag ON character_tags (tag)');
        $this->addSql(<<<'SQL'
            CREATE TABLE dungeons_ref (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              key VARCHAR(255) NOT NULL,
              name VARCHAR(255) NOT NULL,
              level INT NOT NULL,
              image_url TEXT NOT NULL,
              source VARCHAR(100) NOT NULL,
              source_id VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_dungeons_ref_level ON dungeons_ref (level)');
        $this->addSql('CREATE UNIQUE INDEX unique_dungeon_key ON dungeons_ref (key)');
        $this->addSql('CREATE INDEX idx_dungeons_ref_key ON dungeons_ref (key)');
        $this->addSql(<<<'SQL'
            CREATE TABLE professions_ref (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              key VARCHAR(255) NOT NULL,
              name VARCHAR(255) NOT NULL,
              category VARCHAR(50) NOT NULL,
              image_url TEXT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_professions_ref_category ON professions_ref (category)');
        $this->addSql('CREATE INDEX idx_professions_ref_key ON professions_ref (key)');
        $this->addSql('CREATE UNIQUE INDEX unique_profession_key ON professions_ref (key)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_availability
            ADD
              CONSTRAINT fk_e0d327d61136be75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_dungeon
            ADD
              CONSTRAINT fk_565f9fad1136be75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_profession
            ADD
              CONSTRAINT fk_b1fb4ef1136be75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_profile
            ADD
              CONSTRAINT fk_e8f22a321136be75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_quest
            ADD
              CONSTRAINT fk_bdd41f751136be75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_quest_combat
            ADD
              CONSTRAINT fk_abdf04071136be75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_tags
            ADD
              CONSTRAINT fk_784080be1136be75 FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }
}
