<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250426164606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE warnings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description TEXT NOT NULL, character_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6949E6121136BE75 ON warnings (character_id)');
        $this->addSql('CREATE INDEX IDX_6949E612F675F31B ON warnings (author_id)');
        $this->addSql('ALTER TABLE warnings ADD CONSTRAINT FK_6949E6121136BE75 FOREIGN KEY (character_id) REFERENCES characters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE warnings ADD CONSTRAINT FK_6949E612F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE channel_recrutement_message DROP CONSTRAINT fk_channel_recrutement_message_author');
        $this->addSql('DROP TABLE channel_recrutement_author');
        $this->addSql('DROP TABLE channel_recrutement_message');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE channel_recrutement_author (id BIGINT NOT NULL, username TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE channel_recrutement_message (type BIGINT NOT NULL, "timestamp" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, edited_timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, flags BIGINT DEFAULT NULL, content TEXT NOT NULL, author_id BIGINT NOT NULL, id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_53497174F675F31B ON channel_recrutement_message (author_id)');
        $this->addSql('ALTER TABLE channel_recrutement_message ADD CONSTRAINT fk_channel_recrutement_message_author FOREIGN KEY (author_id) REFERENCES channel_recrutement_author (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE warnings DROP CONSTRAINT FK_6949E6121136BE75');
        $this->addSql('ALTER TABLE warnings DROP CONSTRAINT FK_6949E612F675F31B');
        $this->addSql('DROP TABLE warnings');
    }
}
