<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajoute la table blacklist_character : personnages associés (mules/alts)
 * rattachés à une entrée de la blacklist.
 */
final class Version20260818130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add blacklist_character table for associated characters/alts on a blacklist entry';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE blacklist_character (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(255) NOT NULL, ankama_pseudo VARCHAR(255) DEFAULT NULL, blacklist_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BLACKLIST_CHARACTER_BLACKLIST ON blacklist_character (blacklist_id)');
        $this->addSql('ALTER TABLE blacklist_character ADD CONSTRAINT FK_BLACKLIST_CHARACTER_BLACKLIST FOREIGN KEY (blacklist_id) REFERENCES blacklist (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE blacklist_character DROP CONSTRAINT FK_BLACKLIST_CHARACTER_BLACKLIST');
        $this->addSql('DROP TABLE blacklist_character');
    }
}
