<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250102000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create events and event_participants tables';
    }

    public function up(Schema $schema): void
    {
        // Create events table
        $this->addSql('CREATE TABLE events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cash_prize NUMERIC(10, 2) DEFAULT NULL, image VARCHAR(500) DEFAULT NULL, owner_id INT NOT NULL, is_finished BOOLEAN NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5387574A7E3C61F9 ON events (owner_id)');
        
        // Create event_participants table
        $this->addSql('CREATE TABLE event_participants (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_id INT NOT NULL, user_id INT NOT NULL, rank INT DEFAULT NULL, points_earned NUMERIC(10, 2) DEFAULT NULL, prize_received NUMERIC(10, 2) DEFAULT NULL, subscribed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EVENT_PARTICIPANT_EVENT ON event_participants (event_id)');
        $this->addSql('CREATE INDEX IDX_EVENT_PARTICIPANT_USER ON event_participants (user_id)');
        $this->addSql('ALTER TABLE event_participants ADD CONSTRAINT FK_EVENT_PARTICIPANT_EVENT FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE event_participants DROP CONSTRAINT FK_EVENT_PARTICIPANT_EVENT');
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE event_participants');
    }
}




