# nameOverride replace the name of the chart
nameOverride:
# fullnameOverride
fullnameOverride:

## Image configuration
imagesConfiguration:
  global:
    repo:
    tag: 2025-03-11-v1
  custom:
    symfony:
      repo: ghcr.io/erebor-org/erebor/symfony
      tag:
    front:
      repo: ghcr.io/erebor-org/erebor/nginx
      tag:

### Deployments configuration
deployments:
  app:
    labels:
    annotations:
    replicas:
    terminationGracePeriodSeconds:
    containers:
      nginx:
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
        imagePullPolicy:
        config:
          VITE_SYMFONY_URL: https://api.erebor-dofus.fr
      symfony:
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        imagePullPolicy:
        config:
          APP_SECRET:
          DATABASE_URL:
          JWT_PASSPHRASE:
          APP_ENV: prod
          MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
          MAILER_DSN: null://null
          CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
          JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
          JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
### Ingress configuration
### Will automatically bind the hosts to the service

ingress:
  enabled: yes
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls:
    - secretName: erebor-tls
      hosts:
        - erebor-dofus.fr
        - api.erebor-dofus.fr
  hosts:
    - host: erebor-dofus.fr
      paths:
        - path: /
          pathType: Prefix
          serviceName: nginx
          servicePort: 80
    - host: api.erebor-dofus.fr
      paths:
        - path: /
          pathType: Prefix
          serviceName: nginx
          servicePort: 80

# globalLabels will be applied to all deployments and jobs
globalLabels:
# globalAnnotations will be applied to all deployments and jobs
globalAnnotations:

# managedImagePullSecret, pass a base64 encoded version of a
# .dockerconfigjson and it will be created by helm and applied
# to all resources
managedImagePullSecret:

# imagePullSecrets is an object array of imagePullSecrets that will
# be added to all resources.
# exemple value: - name: name-of-secret
imagePullSecrets:
  - name: regcred

services:
  nginx:
    port: 80
