apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: erebor-actions-deployer
  namespace: erebor
subjects:
  - kind: ServiceAccount
    name: default
    namespace: actions-runner-system
roleRef:
  kind: Role
  name: erebor-actions-deployer
  apiGroup: rbac.authorization.k8s.io
