name: CI

on:
  push:
    branches: ["main", "build-prod-workflow"]

permissions:
  contents: read
  packages: write

jobs:
  prepare-builds:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up date-based versioning with increment
        id: set-version
        run: |
          # Get the current date in YYYY-MM-DD format
          CURRENT_DATE=$(date +"%Y-%m-%d")
          echo $CURRENT_DATE
          # Get the latest existing tag for the current date
          git fetch --tags
          LATEST_TAG=$(git tag -l | grep $(date +"%Y-%m-%d") | sort -V | tail -n 1)
          echo "The latest tag is $LATEST_TAG"
          # Extract the current version number (X), if a tag exists
          if [ -n "$LATEST_TAG" ]; then
            CURRENT_VERSION=$(echo "$LATEST_TAG" | sed -E 's/.*-v([0-9]+)/\1/')
            echo "The current version is $CURRENT_VERSION"
            NEW_VERSION=$((CURRENT_VERSION + 1))
            echo "The new version is $NEW_VERSION"
          else
            NEW_VERSION=1
          fi

          # Create the new version tag in the format YYYY-MM-DD-vX
          VERSION="${CURRENT_DATE}-v${NEW_VERSION}"
          echo "The new version is $VERSION"
          echo "::set-output name=version::$VERSION"

  front-build:
    runs-on: self-hosted
    needs: prepare-builds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        env:
          VERSION: ${{ needs.prepare-builds.outputs.version }}
          VITE_SYMFONY_URL: ${{ vars.VITE_SYMFONY_URL }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Build and tag Docker image with the new version
          docker build -f ./frontend/docker/Dockerfile.prod . \
            --build-arg VITE_SYMFONY_URL=$VITE_SYMFONY_URL \
            --tag ghcr.io/$REPO_NAME/nginx:$VERSION
          docker push ghcr.io/$REPO_NAME/nginx:$VERSION

          # Optionally, tag it as 'latest' for development environments
          docker tag ghcr.io/$REPO_NAME/nginx:$VERSION ghcr.io/$REPO_NAME/nginx:latest
          docker push ghcr.io/$REPO_NAME/nginx:latest
          docker logout ghcr.io

  symfony-build:
    runs-on: self-hosted
    needs: prepare-builds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        env:
          VERSION: ${{ needs.prepare-builds.outputs.version }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Build and tag Docker image with the new version
          docker build -f ./backend/docker/Dockerfile.prod . --tag ghcr.io/$REPO_NAME/symfony:$VERSION
          docker push ghcr.io/$REPO_NAME/symfony:$VERSION

          # Optionally, tag it as 'latest' for development environments
          docker tag ghcr.io/$REPO_NAME/symfony:$VERSION ghcr.io/$REPO_NAME/symfony:latest
          docker push ghcr.io/$REPO_NAME/symfony:latest

          docker logout ghcr.io

  create-release:
    runs-on: self-hosted
    # Added prepare-builds as a dependency to ensure the new version is available
    needs: ["prepare-builds", "front-build", "symfony-build"]
    env:
      VERSION: ${{ needs.prepare-builds.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tag the repository with the version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Create a new tag for the current commit
          git tag $VERSION

          # Push the tag back to the repository
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} $VERSION
